[package]
name = "sovvie/wuye"
authors = ["Sovereignty <email@sov.gg>"]
version = "0.3.5"
license = "MIT" # Optional, but good practice
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
description = "A reactive state library built with ECS."

include = ["Wuye", "default.project.json", "LICENSE"]
#exclude = [ "src", ".gitignore", "default.project.json", "sourcemap.json", "README.md", "stylua.toml", "init.meta.json", "aftman.toml", "wally.toml", "selene.toml", ".vscode" ]

# [place]
# shared-packages = "game.ReplicatedStorage.Packages"

# [dependencies]
# Chemical = "sovvie/wuye@0.3.5"
# Promise = "evaera/promise@4.0.0"
# Sift = "csqrl/sift@0.0.11"
# # Spark = "nezuo/spark@0.3.1"
# # Cmdr = "evaera/cmdr@1.12.0"
# t = "osyrisrblx/t@3.1.1"
# TopBarPlus = "legitatx/topbarplus@3.0.5"
# # DeltaCompress = "nezuo/delta-compress@0.1.3"
# # QuickBounds = "unityjaeger/quickbounds@0.3.1"
# # dispense-prop = "khanpython/dispense-prop@4.3.0"
# NumberSpinner = "boatbomber/numberspinner@0.1.0"
# FunctionTween = "bdidk235/functiontween@0.1.2"
# ShiftUnlocked = "yiannis123git/shiftunlocked@2.2.0"
# ColorUtils = "csqrl/colour-utils@1.4.1"
# Ragdoll-Service = "kiy4ku/ragdoll-service@1.0.1"
# # BoatTween = "boatbomber/boattween@1.0.1"  

# # [server-dependencies]
# ProfileStore = "lm-loleris/profilestore@1.0.3"
